### ISSUE TITLE
SUS

### ISSUE THREAD

**Issue by AryanHooshi** [Bardiafa/Free-V2ray-Config#2]
hmmmmm why does the code look so random and unnecessary .... why tf does it need to encode - decode text files ....????
sus

**Comment by AryanHooshi** [comment]
nvm your a life saver the config.txt contained hundreds of profiles and like 5% of them work so 5% of 800 is like 40 config .... ty sm

**Comment by Bardiafa** [comment]
Hi @AryanHooshi ,
i would be happy if _you_ could edit the code & the output to get better results. it needed to be done because it have to get base64 texts from those sources then it decodes it to a usable configs for _v2ray_

**Comment by Bardiafa** [comment]
the code saves the results then push to [configs.txt](https://raw.githubusercontent.com/Bardiafa/Free-V2ray-Config/main/configs.txt) to a usable link.

The connectivity is depending on what ISP you are using already because ISPs are now blocking some IP ranges but some of them not!!

So try them all to get connected

_We are developing the code soon to have subscription link & splitted configs to get best & fastest results_
