### ISSUE TITLE
nothing worked as expected !

### ISSUE THREAD

**Issue by pooooriya** [Bardiafa/Free-V2ray-Config#8]
![image](https://github.com/Bardiafa/Free-V2ray-Config/assets/65160744/5592af21-c525-4f6d-b2fb-d9f8d60ac230)

I think sansorchi can easily see this config and wrote a script as you wrote and restrict them!
do you have any idea about this? 
none of your configs worked and I think you only must keep configs that worked not all the configs 
this approach is not good
the image show your configs that created 9h ago and i took this from your commits

**Comment by Bardiafa** [comment]
Hi pooriya, 
Thanks for creating issue. as other people mentioned earlier in twitter , the internet in Iran is different by every ISP or even city!

**So make sure you use subscription links instead of changes in commits because some may not work on your ISP.**

As you saw the python code , i just gather configs from some places not any special work! so if any of providers closed their link , i would find another way.

All of the providers share their link for people for free (im not stealing from them) , so i dont think they close their way to access (but some users reported that the say bad things behind me :) ).
